WIP - Chapters 4, 5, 6
SebastianElvis/english-research-lint pull request #7
Opened 2020-10-31 13:49 UTC by pykong

- Section numbering and TOC not updated (@SebastianElvis do you got some programmatic way to do this?)
- Added examples to chapter 4
- Added chapter 5 - "The original manuscript
- Add chapter 6 - plagiarism (Noite there is more content in Unit 6 of the course which I did not include because I am not interested in that.)
- Added section on Further Reading

Note:
@SebastianElvis I have collected all changes into a single big changeset out of convenience. If you like to have smaller changesets I need to split it up into smaller chapter-focus PRs.

2020-11-01 03:23 UTC, SebastianElvis commented
Thanks for your continuous contribution!

> * Section numbering and TOC not updated (@SebastianElvis do you got some programmatic way to do this?)

I use VSCode's Markdown plugin, which supports generating ToC automatically. I believe it's based on this project https://github.com/jonschlinkert/markdown-toc. You can run it as a standalone program as well.

> Note:
> @SebastianElvis I have collected all changes into a single big changeset out of convenience. If you like to have smaller changesets I need to split it up into smaller chapter-focus PRs.

It (including everything in a single PR) is okay to me.

2020-11-01 13:48 UTC, pykong commented
@SebastianElvis I have updated section numbering and TOC.
Doing this manually is acceptable for a finite scope project such as this, but for more elaborate cases (e.g. doctoral thesis) `pandoc` is better suited to take care of this task.

Anyway thanks for laying the groundwork of this project.

I am not going to include the other units as they are not focused on writing papers and theses.

2020-11-02 17:19 UTC, pykong commented
@SebastianElvis is there anything missing to get this PR merged?

2020-11-03 01:51 UTC, SebastianElvis requested changes
Other parts are good to me

2020-11-03 01:51 UTC, SebastianElvis commented on README.md
> +- [(WIP) Academic Writing Style Guide for Programmers](#wip-academic-writing-style-guide-for-programmers)
Why is the ToC there?

2020-11-03 08:06 UTC, pykong commented on README.md
> +- [(WIP) Academic Writing Style Guide for Programmers](#wip-academic-writing-style-guide-for-programmers)
Ouch. I missed that. It is fixed now.

2020-11-03 12:32 UTC, SebastianElvis commented
Thanks!

2020-11-03 12:32 UTC, merged